# Generated by Django 4.0.3 on 2022-08-27 15:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('img', models.ImageField(upload_to='banners', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Главные баннеры',
                'verbose_name_plural': 'Главные баннеры',
            },
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название породы')),
            ],
            options={
                'verbose_name': 'Породу',
                'verbose_name_plural': 'Породы',
            },
        ),
        migrations.CreateModel(
            name='Callback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Клиент')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Обработан')),
            ],
            options={
                'verbose_name': 'Заказ звонка',
                'verbose_name_plural': 'Заказ звонка',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=30, verbose_name='Ник')),
                ('avatar', models.ImageField(blank=True, default='', upload_to='feedbacks', verbose_name='Аватарка')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Подтвержен')),
            ],
            options={
                'verbose_name': 'Отзывы',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='OurSalon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('img', models.ImageField(upload_to='outworks', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Фото салона',
                'verbose_name_plural': 'Фоты салона',
            },
        ),
        migrations.CreateModel(
            name='OurWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('img', models.ImageField(upload_to='outworks', verbose_name='Наши работы')),
            ],
            options={
                'verbose_name': 'Наши работы',
                'verbose_name_plural': 'Наши работы',
            },
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('mobile_img', models.ImageField(upload_to='promo', verbose_name='Баннер для моб устройств')),
                ('tablet_img', models.ImageField(upload_to='promo', verbose_name='Баннер для компа')),
            ],
            options={
                'verbose_name': 'Акции',
                'verbose_name_plural': 'Акции',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('punkts', models.TextField(help_text='!!!Каждый тезис писать на новой строке. Это важно. Иначе будет один сплошной текст.', verbose_name='Тезисы')),
            ],
            options={
                'verbose_name': 'Вопрос и ответ',
                'verbose_name_plural': 'Вопросы и ответы',
            },
        ),
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Ник')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('min_price', models.SmallIntegerField(verbose_name='Мин цена')),
                ('services', models.TextField(verbose_name='Услуги')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('current_date', models.DateField(verbose_name='Дата записи')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработан')),
            ],
            options={
                'verbose_name': 'Запись на прием',
                'verbose_name_plural': 'Запись на прием',
            },
        ),
        migrations.CreateModel(
            name='Сategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категорию',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название услуги')),
                ('text', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('animal', models.CharField(choices=[('cat', 'Кошка'), ('dog', 'Собака'), ('any', 'Любая')], default='any', max_length=3, verbose_name='Вид животного')),
                ('price', models.CharField(default='0', max_length=20, verbose_name='Цена')),
                ('time', models.CharField(blank=True, default='', max_length=20, verbose_name='Продолжительность')),
                ('img', models.FileField(upload_to='services', verbose_name='Картинка')),
                ('breed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.breed', verbose_name='Порода')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.сategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Услугу',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
