# Generated by Django 4.0.3 on 2022-08-27 15:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Имя')),
                ('lastname', models.CharField(blank=True, max_length=50, verbose_name='Фамилия')),
                ('avatar', models.ImageField(blank=True, default='', upload_to='masters', verbose_name='Фотка')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Телефон')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Заметки')),
                ('animal', models.CharField(blank=True, default='', max_length=100, verbose_name='Животное')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Имя')),
                ('lastname', models.CharField(blank=True, default='', max_length=50, verbose_name='Фамилия')),
                ('avatar', models.ImageField(blank=True, default='', upload_to='masters', verbose_name='Фотка')),
                ('education', models.CharField(blank=True, default='Без образования', max_length=100, verbose_name='Образование')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Телефон')),
                ('post', models.CharField(choices=[('main_groommer', 'Главный груммер'), ('groommer', 'Груммер'), ('helper', 'Помощник груммера')], default='groommer', max_length=20, verbose_name='Должность')),
                ('color', models.CharField(default='#FFC11C', max_length=10, verbose_name='Цвет')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Заметки')),
                ('rate', models.SmallIntegerField(blank=True, default=0, verbose_name='Ставка')),
                ('address', models.CharField(blank=True, default='', max_length=50, verbose_name='Адрес')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Грумер',
                'verbose_name_plural': 'Грумеры',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название товара')),
                ('vendor_code', models.CharField(blank=True, default='', max_length=30, verbose_name='Артикул')),
                ('count', models.SmallIntegerField(blank=True, default=0, verbose_name='Количество')),
                ('price', models.IntegerField(blank=True, default=0, verbose_name='Цена')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('img', models.FileField(blank=True, null=True, upload_to='services', verbose_name='Картинка')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='OrderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.SmallIntegerField(blank=True, default=0, verbose_name='Количество')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Услуга заказа',
                'verbose_name_plural': 'Услуги заказов',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.SmallIntegerField(blank=True, default=0, verbose_name='Количество')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Товар заказа',
                'verbose_name_plural': 'Товары заказов',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.SmallIntegerField(blank=True, default=0, verbose_name='Цена')),
                ('is_success', models.BooleanField(blank=True, default=False, verbose_name='Оплачен')),
                ('is_cancel', models.BooleanField(blank=True, default=False, verbose_name='Отменен')),
                ('is_reserved', models.BooleanField(blank=True, default=False, verbose_name='Забронирован')),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата обновления')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
                ('client', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.client', verbose_name='Клиент')),
                ('master', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.master', verbose_name='Мастер')),
                ('products', models.ManyToManyField(blank=True, to='app.orderproduct', verbose_name='Продукты')),
                ('services', models.ManyToManyField(blank=True, to='app.orderservice', verbose_name='Услуги')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название записи')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время записи')),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время окончания')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('is_success', models.BooleanField(blank=True, default=False, verbose_name='Выполнен')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата обновления')),
                ('client', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.client', verbose_name='Клиент')),
                ('master', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.master', verbose_name='Мастер')),
                ('services', models.ManyToManyField(blank=True, to='app.service', verbose_name='Услуги')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
    ]
