# Generated by Django 4.0.3 on 2022-09-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_client_master_product_orderservice_orderproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Адрес'),
        ),
    ]
