# Generated by Django 4.0.3 on 2022-09-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_client_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='services', verbose_name='Картинка'),
        ),
    ]
