# Generated by Django 4.0.3 on 2022-09-05 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_service_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Сategory',
            new_name='Category',
        ),
    ]
