# Generated by Django 4.0.3 on 2022-09-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_сategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='products', verbose_name='Картинка'),
        ),
    ]
