# Generated by Django 4.0.3 on 2022-09-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_blocked',
            field=models.BooleanField(blank=True, default=False, verbose_name='Заблокирован'),
        ),
    ]
