# Generated by Django 4.0.3 on 2022-09-25 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_client_is_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderservice',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.service', verbose_name='Услуга'),
        ),
    ]
