# Generated by Django 4.0.3 on 2023-03-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_service_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='show',
            field=models.BooleanField(default=True, verbose_name='Отображать'),
        ),
    ]
