# Generated by Django 4.0.3 on 2023-09-30 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_breed_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='breed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.breed', verbose_name='Порода'),
        ),
        migrations.AlterField(
            model_name='service',
            name='img',
            field=models.FileField(null=True, upload_to='services', verbose_name='Картинка'),
        ),
    ]
