# Generated by Django 4.0.3 on 2024-03-05 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_smsnotification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smsnotification',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='smsnotification',
            old_name='user_id',
            new_name='user',
        ),
    ]
