# Generated by Django 4.0.3 on 2024-03-05 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_order_id_smsnotification_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsnotification',
            name='order',
        ),
    ]
