# Generated by Django 4.0.3 on 2024-04-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_category_is_notificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_notificate',
            field=models.BooleanField(default=True, verbose_name='Уведомлять?'),
        ),
    ]
