# Generated by Django 4.0.3 on 2024-04-07 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_client_is_notificate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SmsNotification',
        ),
    ]
