# Generated by Django 4.0.3 on 2025-03-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_category_is_notificate_service_is_notificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='show',
            field=models.BooleanField(default=True, verbose_name='Отображать'),
        ),
    ]
