name: CI

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - uses: fifsky/ssh-action@master
        with:
          command: |
            cd ~/grummers
            git pull
            source env/bin/activate
            rm -rf static/*
            ./manage.py collectstatic
            sudo /etc/init.d/supervisor start
          host: ${{secrets.HOST}}
          user: root
          key: ${{secrets.SSH_PRIVATE_KEY}}
          args: "-tt"
