name: CI

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - uses: fifsky/ssh-action@master
        with:
          command: |
            cd ~/grummers
            source env/bin/activate
            ./manage.py crontab remove
            git pull
            pip install -r requirements.txt
            rm -rf ~/grummers/static/*
            ./manage.py collectstatic
            ./manage.py makemigrations
            ./manage.py migrate
            killall gunicorn
            ./manage.py crontab add
          host: ${{secrets.HOST}}
          user: www
          key: ${{secrets.SSH_PRIVATE_KEY}}
          args: "-tt"
