name: CI

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - uses: fifsky/ssh-action@master
        with:
          command: |
            cd ~/grummers
            git pull
          host: ${{secrets.HOST}}
          user: www
          key: ${{secrets.SSH_PRIVATE_KEY}}
          args: "-tt"
